#!/bin/bash

set -xeuo pipefail

bazel test --config debian "$@" -- //... -//rpm/...
bazel test --config fedora "$@" -- //... -//rpm/...
bazel test --config ubuntu "$@" -- //... -//rpm/...
bazel test --config rocky "$@" -- //...
bazel test --config centos "$@" -- //...
