#!/bin/bash

set -xeuo pipefail

bazel test --config debian "$@" -- //...
bazel test --config fedora "$@" -- //...
bazel test --config ubuntu "$@" -- //...
bazel test --config rocky "$@" -- //...
bazel test --config centos "$@" -- //...
